

```{r}
#Make the rotation matrix
rotation_matrix <- function(t){
  tv <- strsplit(t, "")[[1]] # split string
  tvtv <- rep(tv, 2) # repeated vector for rotations
  bwm <- matrix(ncol = length(tv), nrow = length(tv)) # empty matrix
  
  for(i in seq(tv)){
    bwm[i,] <- tvtv[i:(i-1+length(tv))] # make rotations
  }
  bwm <- bwm[do.call(order, as.data.frame(bwm)),] # order starting from first column
  return(bwm)
}

#Burrows Wheeler transformation
bwt <- function(t){
  bwm <- rotation_matrix(t) # make rotation matrix
  Last <- bwm[,ncol(bwm)] # get last column
  return(paste(Last, collapse = "")) # return in string
}

```

```{r}
# Function to encode a single nucleotide
encode <- function(DNA_encode) {
         switch(DNA_encode,
         "A" = "00",
         "C" = "01",
         "G" = "10",
         "T" = "11",
         stop("Invalid DNA_encode"))
}

# Function to encode a whole DNA sequence
encode_dna_sequence <- function(dna_sequence) {
  # Split the sequence into individual nucleotides
  a <- unlist(strsplit(dna_sequence, ""))
  # Encode each DNA_encode
  b <- sapply(a, encode)
  # Collapse the binary codes into a single string
  paste(b, collapse = "")
}

# Encode the GATTACA sequence
dna_sequence <- "GATTACA"
binary <- encode_dna_sequence(dna_sequence)

# Output the result
cat(binary)
```

```{r}
#Reverse BWT
rank_bw <- function(bw){
  bwv <- strsplit(bw, "")[[1]] # split string in vector
  totals <- c() # empty totals vector
  rank <- rep(NA, length(bwv)) # empty rank vector with predefined size
  for(i in seq(bwv)){
    if(!(bwv[i] %in% names(totals))){ # add to item to totals if doesn't exist
      totals[bwv[i]] <- 1 # add make it 1
    } else {
      totals[bwv[i]] <- totals[bwv[i]] + 1 # add 1 to totals for that character
    }
    rank[i] <- totals[bwv[i]] # fill the rank vector with rank
  }
  return(list(totals = totals, rank = rank)) # return a list of with totals and rank
}

get_first <- function(totals){
  totals <- totals[order(names(totals))] # order alpabetically on character
  FirstL <- list() # empty list
  for(char in names(totals)){
    FirstL[[char]] <- data.frame(c = rep(char, totals[char]),
                                 n = 1:totals[char]) # make a data.frame for each character with ascending rank
  }
  return(do.call(rbind, FirstL)) # return concatenated data.frame
}

reverse_bwt <- function(bw){
  bwv <- strsplit(bw, "")[[1]] # split string in vector
  rank_list <- rank_bw(bw) # call rank_bw
  totals <- rank_list$totals # get totals vector
  rank <- rank_list$rank # get rank vector
  First <- get_first(totals) # get data.frame of First with rank
  i <- 1
  out <- "$" # start building from last character, so with the dollarsign (eof)
  while(bwv[i] != "$"){ # if dollarsign is found again, you're finished
    appchar <- bwv[i] # get character that appends before last found character
    out <- paste0(appchar, out) # append character 
    i <- which(First$c == appchar)[1] + rank[i] - 1 # find character with rank in First based on rank of character in last
  }
  return(paste(out, collapse = ""))
}

```

```{r}
bw_transformed <- bwt("GATTACA$")
bw_transformed
reverse_bwt(bw_transformed)
```

